[versions]
appVersionCode = "596"
appVersionName = "1.23.6"
androidGradlePlugin = "8.13.0"
kotlin = "2.2.20"
dagger = "2.57.2"
gmsPlugin = "4.4.3"
firebaseCrashlyticsPlugin = "3.0.6"
ksp = "2.2.20-2.0.3"
ideaExt = "1.3"
androidxBaselineProfile = "1.4.1"
androidxCore = "1.17.0"
androidxCoreI18n = "1.0.0"
androidxAppCompat = "1.7.1"
androidxActivity = "1.11.0"
androidxFragment = "1.8.9"
androidxBrowser = "1.9.0"
androidxMedia3 = "1.8.0"
androidxMedia = "1.7.1"
androidxMediaRouter = "1.8.1"
androidxMultidex = "2.0.1"
androidxMultidexInstrumentation = "2.0.0"
androidxWebkit = "1.14.0"
androidxCollection = "1.5.0"
androidxLifecycle = "2.9.4"
androidxNavigation = "2.9.5"
androidxHiltNavCompose = "1.2.0"
androidxSplashScreen = "1.0.1"
androidxPaging = "3.3.6"
androidxStartup = "1.2.0"
androidxDatastorePref = "1.1.7"
androidxAnnotation = "1.9.1"
androidxProfileInstaller = "1.4.1"
androidxComposeBom = "2025.09.01"
androidxTvMaterial = "1.0.1"
androidxTest = "1.7.0"
androidxTestJunit = "1.3.0"
androidxEspresso = "3.7.0"
androidxUiautomator = "2.3.0"
androidxBenchmarkJunit4 = "1.4.1"
googleCast = "22.1.0"
googleCastTv = "21.1.1"
reorderable = "3.0.0"
retrofit = "3.0.0"
kotlinxSerialization = "1.9.0"
kotlinxCoroutines = "1.10.2"
okhttp3 = "4.12.0"
coil = "3.3.0"
timber = "5.0.1"
firebaseBom = "33.16.0"
leakcanary = "2.14"
desugarJdkLibs = "2.1.5"
junit = "4.13.2"
mockk = "1.14.5"
assertk = "0.28.1"
jsonassert = "1.5.3"
processPhoenix = "3.0.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-i18n = { group = "androidx.core", name = "core-i18n", version.ref = "androidxCoreI18n" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "androidxFragment" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidx-media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "androidxMedia3" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "androidxMedia" }
androidx-mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "androidxMediaRouter" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "androidxMultidex" }
androidx-multidex-instrumentation = { group = "androidx.multidex", name = "multidex-instrumentation", version.ref = "androidxMultidexInstrumentation" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit" }
androidx-collection = { group = "androidx.collection", name = "collection", version.ref = "androidxCollection" }
androidx-lifecycle-vm = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-vm-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-hilt-nav-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavCompose" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartup" }
androidx-datastore-pref = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePref" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileInstaller" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics-android" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "androidxTvMaterial" }
androidx-test = { group = "androidx.test", name = "core", version.ref = "androidxTest" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestJunit" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiautomator" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxBenchmarkJunit4" }
google-cast-framework = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "googleCast" }
google-cast = { group = "com.google.android.gms", name = "play-services-cast", version.ref = "googleCast" }
google-cast-tv = { group = "com.google.android.gms", name = "play-services-cast-tv", version.ref = "googleCastTv" }
reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reorderable" }
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
okhttp3-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp3" }
okhttp3-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp3" }
coil-bom = { group = "io.coil-kt.coil3", name = "coil-bom", version.ref = "coil" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp" }
coil-cachecontrol = { group = "io.coil-kt.coil3", name = "coil-network-cache-control" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
process-phoenix = { group = "com.jakewharton", name = "process-phoenix", version.ref = "processPhoenix" }
google-firebase = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }
jsonassert = { group = "org.skyscreamer", name = "jsonassert", version.ref = "jsonassert" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxBaselineProfile"}
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "ideaExt" }
