name: build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle
      - uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
      - name: Prepare keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FILE_PASSPHRASE }}" --batch keystore.jks.asc > app/keystore.jks
      - name: Write keystore secrets to environment
        run: |
          echo "ORG_GRADLE_PROJECT_RAINWAVE_TEST_CREDENTIALS=${{ secrets.RAINWAVE_TEST_CREDENTIALS }}" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_RELEASE_STORE_FILE=keystore.jks" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS=${{ secrets.UPLOAD_KEY_ALIAS }}" >> "$GITHUB_ENV"
          echo "ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD=${{ secrets.UPLOAD_KEY_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean
        run: ./gradlew clean
      - name: Run tests
        run: ./gradlew app:test
      - name: Build AAB with Gradle
        run: ./gradlew bundleRelease
      - name: Build universal APK from AAB
        run: |
          json=$(curl -s https://api.github.com/repos/google/bundletool/releases/latest)
          downloadUrl=$(echo $json | jq -r ".assets | .[].browser_download_url")
          curl $downloadUrl -4 -sL -o 'bundletool.jar'
          java -jar bundletool.jar build-apks --bundle=app/build/outputs/bundle/release/app-release.aab --output=app.apks \
            --mode=universal \
            --ks=app/keystore.jks \
            --ks-pass=pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --ks-key-alias=${{ secrets.RELEASE_KEY_ALIAS }} \
            --key-pass=pass:${{ secrets.RELEASE_KEY_PASSWORD }}
          unzip app.apks -d .
          mkdir -p app/build/outputs/apk/release
          mv universal.apk app/build/outputs/apk/release/app-release.apk
      - name: Upload apk/aab
        uses: actions/upload-artifact@v4
        with:
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: error
